name: workiom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  encrypt: ^5.0.1
  get: ^4.6.6
  get_storage: ^2.0.3
  logger: ^1.1.0
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  google_fonts: ^6.1.0
  flutter_form_builder: ^9.1.1
  flutter_svg: ^2.0.7
  timezone: ^0.9.2
  flutter:
    sdk: flutter
    
dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  platform: ^3.1.0

flutter: 
  assets: 
    - assets/locales/
    - assets/images/
  uses-material-design: true

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Thin.ttf
          weight: 100
        - asset: assets/fonts/gilroy/Gilroy-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/gilroy/Gilroy-UltraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/gilroy/Gilroy-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy/Gilroy-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Semibold.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
          weight: 700
        - asset: assets/fonts/gilroy/Gilroy-HeavyItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/gilroy/Gilroy-ExtraboldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Black.ttf
          weight: 900
        - asset: assets/fonts/gilroy/Gilroy-BlackItalic.ttf
          weight: 900
          style: italic
    - family: GT Walsheim
      fonts:
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-ThinOblique.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-UltraLightOblique.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-Light.ttf
          weight: 300
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-LightOblique.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-RegularOblique.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-MediumOblique.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-BoldOblique.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-Black.ttf
          weight: 800
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-BlackOblique.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-UltraBold.ttf
          weight: 900
        - asset: assets/fonts/gt_walsheim/GTWalsheimPro-UltraBoldOblique.ttf
          weight: 900
          style: italic

